version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.VSSDK.BuildTools
    versions:
    - 16.10.10
    - 16.10.23
    - 16.10.31
    - 16.10.7
    - 16.9.1044
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
